### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by draffensperger** [jorendorff/rust-grammar#1]
Cool that you worked on this!

Could you please add a license to this (e.g. Apache 2.0) that specifies how others can use this code?

Right now it's open source, which is great but the lack of a clear license means I'm hesitant to use this for anything official.

**Comment by jorendorff** [comment]
I'll add a license (MIT & Apache, like Rust) but more importantly this needs a README. The grammar may be inaccurate, mainly by being too permissive or by missing newer language features. As a parser, it may also be very slow! But I hope it's helpful as a starting point. :)

Note that <https://github.com/rust-lang/rust/blob/master/src/grammar/parser-lalr.y> is more up-to-date.

**Comment by jorendorff** [comment]
Thanks for the issue, btw!
